# Generated by Django 3.0.5 on 2020-05-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('confirmPassword', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('pincode', models.CharField(max_length=6)),
                ('storeType', models.CharField(max_length=32)),
                ('size', models.CharField(max_length=32)),
                ('employees', models.PositiveIntegerField()),
                ('customers', models.PositiveIntegerField()),
                ('service', models.CharField(max_length=32)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Customer')),
            ],
        ),
    ]
