# Generated by Django 3.0.5 on 2020-05-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200510_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='customers',
            new_name='customersPerDay',
        ),
    ]
