# Generated by Django 2.2 on 2020-05-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200525_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='storename',
            new_name='storeName',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='typestore',
            new_name='typeStore',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='workingemployees',
            new_name='workingEmployees',
        ),
        migrations.AddField(
            model_name='store',
            name='feedback',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='store',
            name='program',
            field=models.CharField(default='Locker', max_length=32),
            preserve_default=False,
        ),
    ]
