# Generated by Django 2.2 on 2020-05-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200525_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='customers',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='email',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='storeName',
            new_name='storename',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='typeStore',
            new_name='typestore',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='employees',
            new_name='workingemployees',
        ),
    ]
