# Generated by Django 3.0.6 on 2020-06-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200527_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='service',
            new_name='ownedRented',
        ),
    ]
